try:
    print(name)
    print(42/0)
except NameError:
    print("Got exeption")
